name: Main

on:
  push:
    branches:
      - main

concurrency:
  group: main-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/_ci.yml
    permissions:
      contents: read

  release-draft:
    needs: ci
    permissions:
      contents: write
    uses: ./.github/workflows/_release-draft.yml
