name: Main

on:
  push:
    branches:
      - main

concurrency:
  group: main-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  release-draft:
    permissions:
      contents: write
    uses: ./.github/workflows/_release-draft.yml
