name: Release

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  container-image:
    if: startsWith(github.event.release.tag_name, 'v')
    name: Stable container image
    uses: ./.github/workflows/_container-image.yml
    with:
      tags: ${{ github.event.release.tag_name }},latest
